services:
  neo4j:
    image: neo4j:5.15.0
    container_name: got_graph
    ports:
      - "7474:7474" # Puerto HTTP (Navegador)
      - "7687:7687" # Puerto Bolt (Python Driver)
    environment:
      NEO4J_AUTH: neo4j/password # Usuario/Contraseña (Cámbialo si quieres)
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 1G
    volumes:
      - ./data/neo4j_data:/data # Persistencia (para no perder datos al apagar)